<a href="https://colab.research.google.com/github/JP109/ML-Basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **0. Import**

In [1]:
import numpy as np

# **1. Basics**

In [2]:
# Create 1D numpy array
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
# Create 2D numpy array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Get dimension
b.ndim

2

In [5]:
# Get shape
b.shape

(2, 3)

In [6]:
# Get type
b.dtype

dtype('int64')

In [7]:
# Get size (in bytes)
a.itemsize

4

In [8]:
# Get no. of elements
a.size

3

In [9]:
# Get total size (a.nbytes=a.itemsize*a.size)
a.nbytes

12

# **2. Accessing/Changing elements/rows/columns**

In [86]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r,c]:
a[1,0]

8

In [12]:
# Get a specific row:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column:
a[:,6]

array([ 7, 14])

In [14]:
# Get a range from a 1D array, with a stepsize [startIndex:endIndex+1:stepSize]
a[0,0:6:2]

array([1, 3, 5])

In [87]:
# *** You can index with a list too:
a[0,[3,4]]

array([4, 5])

In [93]:
np.any(a>9)

True

In [94]:
np.all(a>9)

False

In [95]:
np.any(a>9, axis=0)

array([False, False,  True,  True,  True,  True,  True])

In [96]:
np.all(a>9, axis=0)

array([False, False, False, False, False, False, False])

In [97]:
((a>4) & (a<9))

array([[False, False, False, False,  True,  True,  True],
       [ True, False, False, False, False, False, False]])

In [98]:
# Masking:
(~((a>4) & (a<9)))

array([[ True,  True,  True,  True, False, False, False],
       [False,  True,  True,  True,  True,  True,  True]])

In [15]:
# Change an element:
a[1,5]=22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [16]:
a[:,2]=50
print(a)

[[ 1  2 50  4  5  6  7]
 [ 8  9 50 11 12 22 14]]


In [17]:
a[:,0]=[8,9]
print(a)

[[ 8  2 50  4  5  6  7]
 [ 9  9 50 11 12 22 14]]


In [18]:
# 3D example
b=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [19]:
# Get specific element (work outside in)
b[0,1,1]

4

In [20]:
b[:,1,:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

# **3. Initializing different kinds of arrays**

In [21]:
# All zero matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All ones matrix
np.ones((3,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [23]:
# Any other number
np.full((4,2,2),99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [24]:
# Any other number, with previously defined array for shape:
np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [25]:
# Random decimal no.s:
np.random.rand(4,2)

array([[0.90641816, 0.65534272],
       [0.06849478, 0.39435099],
       [0.98522382, 0.25481899],
       [0.93483309, 0.46364463]])

In [27]:
# Random integer no.s:
np.random.randint(-3,9,size=(3,3))

array([[ 3, -2, -2],
       [ 7,  0, -1],
       [ 4,  1, -3]])

In [28]:
# Identity matrix:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Repeat an array
arr=np.array([[1,2,3]])
np.repeat(arr,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# **4. Copying arrays**

In [31]:
# Copy by reference:
e=np.array([1,2,3])
f=e
f[0]=88
e

array([88,  2,  3])

In [32]:
# Copy by value:
i=np.array([1,2,3])
j=i.copy()
j[0]=88
i

array([1, 2, 3])

# **5. Mathematics**

In [42]:
# All math operations are element-wise
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 2

array([3, 4, 5, 6])

In [44]:
a - 1

array([0, 1, 2, 3])

In [45]:
a * 2

array([2, 4, 6, 8])

In [46]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [47]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [48]:
# Trigo functions
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# **6. Linear Algebra**

In [54]:
a = np.ones((2,3))
b = np.full((3,2), 2)
print('a :{}'.format(a))
print('b :{}'.format(b))

a :[[1. 1. 1.]
 [1. 1. 1.]]
b :[[2 2]
 [2 2]
 [2 2]]


In [51]:
a*b
# Gives an error because python operators are element wise

ValueError: ignored

In [52]:
# Matrix cross multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [55]:
# Matrix dot product
np.dot(a,b)

array([[6., 6.],
       [6., 6.]])

In [57]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [58]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## **7. Statistics**

In [62]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# Minimum
np.min(stats)

1

In [64]:
# Maximum
np.max(stats)

6

In [65]:
np.min(stats,axis=1)

array([1, 4])

In [66]:
np.min(stats, axis=0)

array([1, 2, 3])

In [67]:
# Sum
np.sum(stats)

21

In [69]:
# Sum
np.sum(stats, axis=0)

array([5, 7, 9])

# **8. Reorganizing arrays**

In [72]:
# Reshaping arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [74]:
# Vertically stacking arrays:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
# Horizontally stacking arrays:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])