<a href="https://colab.research.google.com/github/JP109/ML-Basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **0. Import**

In [1]:
import numpy as np

# **1. Basics**

In [3]:
# Create 1D numpy array
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [6]:
# Create 2D numpy array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# Get dimension
b.ndim

2

In [8]:
# Get shape
b.shape

(2, 3)

In [10]:
# Get type
b.dtype

dtype('int64')

In [15]:
# Get size (in bytes)
a.itemsize

4

In [16]:
# Get no. of elements
a.size

3

In [17]:
# Get total size (a.nbytes=a.itemsize*a.size)
a.nbytes

12

# **2. Accessing/Changing elements/rows/columns**

In [19]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
# Get a specific element [r,c]:
a[1,0]

8

In [22]:
# Get a specific row:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column:
a[:,6]

array([ 7, 14])

In [26]:
# Get a range from a 1D array, with a stepsize [startIndex:endIndex:stepSize]
a[0,0:6:2]

array([1, 3, 5])

In [28]:
# Change an element:
a[1,5]=22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 22 14]]


In [29]:
a[:,2]=50
print(a)

[[ 1  2 50  4  5  6  7]
 [ 8  9 50 11 12 22 14]]


In [31]:
a[:,0]=[8,9]
print(a)

[[ 8  2 50  4  5  6  7]
 [ 9  9 50 11 12 22 14]]


In [35]:
# 3D example
b=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]],
            [[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [36]:
# Get specific element (work outside in)
b[0,1,1]

4

In [37]:
b[:,1,:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])